name: training_app
description: "Keep training. Together."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  super_clipboard: ^0.9.1
  hive_ce: ^2.4.2
  hive_ce_flutter: ^2.0.1
  uuid: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.6.1
  build_runner: ^2.4.6
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
